# # encoding: utf-8

# Inspec test for recipe assets::default

# The Inspec reference, with examples and extensive documentation, can be
# found at http://inspec.io/docs/reference/resources/

describe directory('/var/canvas/log') do
  its('owner') { should eq 'canvasuser'}
  it { should be_directory}
end

describe directory('/var/canvas/tmp/pids') do
  its('owner') { should eq 'canvasuser'}
  it { should be_directory}
end

describe directory('/var/canvas/public/assets') do
  its('owner') { should eq 'canvasuser'}
  it { should be_directory}
end

describe directory('/var/canvas/app/stylesheets/brandable_css_brands') do
  its('owner') { should eq 'canvasuser'}
  it { should be_directory}
end

describe file('app/stylesheets/_brandable_variables_defaults_autogenerated.scss') do
  it { should be_file}
  its('owner') { should eq 'canvasuser'}
end

describe file('Gemfile.lock') do
  it { should be_file}
  its('owner') { should eq 'canvasuser'}
end

describe file('log/production.log') do
  it { should be_file}
  its('owner') { should eq 'canvasuser'}
end
