---
AWSTemplateFormatVersion: 2010-09-09
Description: VPC definition.
Metadata:
  Role: network
Parameters:
  Environment:
    Description: "Enter shared, dev1, devf, mint, demo, stge, prod. Default is mint."
    Type: String
    Default: mint
    AllowedPattern: ^(shared|production|staging|demo|mint|int-[a-z]+)$
Outputs:
  VPC:
    Value: !Ref VPC
    Export:
      Name: !Sub "${Environment}-vpc"
  VPCCidr:
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Sub "${Environment}-vpc-cidr"
  PublicAcl:
    Value: !Ref PublicNetworkAcl
    Export:
      Name: !Sub "${Environment}-public-acl"
  PrivateAcl:
    Value: !Ref PrivateNetworkAcl
    Export:
      Name: !Sub "${Environment}-private-acl"
  DnsIp:
    Value: !FindInMap [ Environments, !Ref Environment, DnsIp ]
    Export:
      Name: !Sub "${Environment}-dns-ip"

Mappings:
# Assuming Export names must be unique within a region and AWS account.
  Environments:
    shared:
      VPCCidr: "10.0.0.0/16"
      DnsIp: 10.0.0.2
    mint:
      VPCCidr: "10.3.0.0/16"
      DnsIp: 10.3.0.2
    int-as:
      VPCCidr: "10.8.0.0/16"
      DnsIp: 10.8.0.2
    int-bl:
      VPCCidr: "10.5.0.0/16"
      DnsIp: 10.5.0.2
    int-kl:
      VPCCidr: "10.6.0.0/16"
      DnsIp: 10.6.0.2
    int-ls:
      VPCCidr: "10.7.0.0/16"
      DnsIp: 10.7.0.2
    int-rh:
      VPCCidr: "10.14.0.0/16"
      DnsIp: 10.14.0.2
    demo:
      VPCCidr: "10.10.0.0/16"
      DnsIp: 10.10.0.2
    stge:
      VPCCidr: "10.11.0.0/16"
      DnsIp: 10.11.0.2
    prod:
      VPCCidr: "10.12.0.0/16"
      DnsIp: 10.12.0.2
    staging:
      VPCCidr: "10.100.0.0/16"
      DnsIp: 10.100.0.2
    production:
      VPCCidr: "10.200.0.0/16"
      DnsIp: 10.200.0.2
Resources:
  ###
  ### VPC Definition
  ###
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock:
        !FindInMap [Environments, !Ref Environment, VPCCidr]
      EnableDnsHostnames: "true"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${Environment}-vpc"
        - Key: Role
          Value: vpc
  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
          !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub "${Environment}-public-acl"
      - Key: Environment
        Value: !Ref Environment
      - Key: Network
        Value: Public
      - Key: Role
        Value: vpc
  PrivateNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub "${Environment}-private-acl"
      - Key: Environment
        Value: !Ref Environment
      - Key: Network
        Value: Private
      - Key: Role
        Value: vpc
