# # encoding: utf-8

# Inspec test for cookbooks

describe package ('git') do
  it { should be_installed }
end

describe package ('ruby2.4') do
  it { should be_installed }
  its('version') { should cmp >= '2.4.3'}
end

describe package ('yarn') do
  it { should be_installed }
  its('version') { should cmp >= '1.10'}
end

describe package ('python') do
  it { should be_installed }
end

%w{ amazon_s3 database delayed_jobs domain file_store outgoing_mail security external_migration }.each do |config|
  describe file("/var/canvas/config/#{config}.yml") do
    it { should exist }
    its('mode') { should cmp '00400'}
    its('owner') {should eq 'canvasuser'}
  end
end

%w{log tmp/pids public/assets app/stylesheets/brandable_css_brands}.each do |dir|
  describe directory("/var/canvas/#{dir}") do
    its('mode') { should cmp '00755' }
    its('owner') { should eq 'canvasuser' }
    its('group') { should eq 'canva' }
  end
end

%w{app/stylesheets/_brandable_variables_defaults_autogenerated.scss Gemfile.lock log/production.log}.each do |fil|
  describe file("/var/canvas/#{fil}") do
    its('mode') { should cmp '00755' }
    its('owner') { should eq 'canvasuser' }
    its('group') { should eq 'canva' }
  end
end

%w{ rewrite passenger ssl }.each do |modules|
  describe file("/etc/apache2/mods-enabled/#{modules}.load") do
    it { should exist}
  end
end
